### ISSUE TITLE
Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.

### ISSUE THREAD

**Issue by itMcdull** [Wayaer/fl_umeng#10]
`buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        maven { url "https://maven.aliyun.com/repository/public" }
        maven { url "https://maven.aliyun.com/repository/google" }
        maven { url "https://maven.aliyun.com/repository/gradle-plugin" }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }/*  */
}`
`
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip`
提示如下
`The class is loaded from /Users/edy/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.30/d68efdea04955974ac1020f8f66ef8176bfbce1f/kotlin-stdlib-1.5.30.jar!/kotlin/Unit.class
e: /Users/edy/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fl_umeng-2.2.0/android/src/main/kotlin/fl/umeng/UMengPlugin.kt: (114, 17): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /Users/edy/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.30/d68efdea04955974ac1020f8f66ef8176bfbce1f/kotlin-stdlib-1.5.30.jar!/kotlin/Unit.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fl_umeng:compileDebugKotlin'.
> Compilation error. See log for more details`
一定要修改kotlin版本 能否支持低版本的kotlin

**Comment by Wayaer** [comment]
可以升级下自己项目的kotlin版本
