### ISSUE TITLE
IOS上无法编译

### ISSUE THREAD

**Issue by virskor** [Wayaer/fl_umeng#13]
![image](https://user-images.githubusercontent.com/16968535/149880793-4b0c9f5e-cb6e-4892-b7c2-8603d8d410fe.png)

No known class method for selector 'enableNetworkForProtocol:'

[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale zh-Hans)
    • Flutter version 2.8.1 at /Users/virs/fvm/versions/2.8.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 周前), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/virs/Library/Android/sdk
    • Platform android-32, build-tools 30.0.3
    • ANDROID_HOME = /Users/virs/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008030-001231D80231802E • ios            • iOS 15.1 19B74
    • macOS (desktop) • macos                     • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 97.0.4692.71

• No issues found!

**Comment by virskor** [comment]
已经移除PodFile重新安装，flutter clean， 但没用，注释掉这行的话可以编译

**Comment by virskor** [comment]
fl_umeng: ^2.5.0

**Comment by Wayaer** [comment]
cd ios
pod update

**Comment by Wayaer** [comment]
更新下，友盟sdk的版本，一些合规指南。

**Comment by virskor** [comment]
还真是，我更新了好了。忽略了

**Comment by virskor** [comment]
DONE
