### ISSUE TITLE
安卓没有数据。

### ISSUE THREAD

**Issue by bytehola** [Wayaer/fl_umeng#18]
注册成功显示true，集成测试也不显示数据，我也不清楚我哪错了， 后来我把作者的例子代码复制到我的flutter项目，改了appkey之后启动也无数据，可以intent唤起app，但是开始测试也是无数据。

**Comment by Wayaer** [comment]
友盟现在好像不能实时看到数据了，你可以用多个设备测试下看看

**Comment by bytehola** [comment]
> 友盟现在好像不能实时看到数据了，你可以用多个设备测试下看看

直接用您的github上的flutter例子项目也无法正常发送数据，我用了官方提供的sdk，倒是正常。

**Comment by Wayaer** [comment]
有日志么？目前我所有的项目 使用都是正常的，数据 隔天才能有记录，
