### ISSUE TITLE
升级插件后新版本统计不上数据

### ISSUE THREAD

**Issue by nnianhouss** [Wayaer/fl_umeng#20]
我升级最新版本后，友盟后台最新版本号能看到，然后只有零零散散的数据，这是啥情况。

**Comment by nnianhouss** [comment]
我开启日志为哈只能看到这个日志 没有其它信息，这正常吗？ 
D/UMLog (28970): 当前发送策略为：启动时发送。详见链接 https://developer.umeng.com/docs/66632/detail/66976?um_channel=sdk

**Comment by Wayaer** [comment]
插件初始化 需要2次 一次预初始化 一次正式初始化，或者有些ios 启动时 是没有网络的，要等1到2秒才会有网络哦，看是不是这些原因

**Comment by Wayaer** [comment]
这次更新 没有修改任何api，只是 更新了一些配置信息
