### ISSUE TITLE
ios有数据上报,android没有?

### ISSUE THREAD

**Issue by KeyX-y** [Wayaer/fl_umeng#22]
按照作者的配置ios有数据上报, android任何数据没有, 同时也没有报错. 奇怪了

**Comment by Wayaer** [comment]
有调用预初始化么？

**Comment by iOSyan** [comment]
遇到同样的问题，iOS数据有，安卓没有任何数据。

` final bool? data = await FlUMeng().init(
        preInit: true,
        androidAppKey: androidAppKey
        iosAppKey: iosAppKey,
        channel: 'channel');`

   ` debugPrint('Umeng 初始化成功 = $data');`
打印结果是true，但是数据没有统计。

**Comment by Wayaer** [comment]
> 
预初始化
`FlUMeng().init( preInit: true)`
正式初始化
`FlUMeng().init( preInit: false)`
初始化方法需要调用两次一次预初始化 一次正式初始化， 预初始化一般放在同意授权之前，正式初始化放在授权之后

**Comment by iOSyan** [comment]
预初始化
FlUMeng().init( preInit: true)
正式初始化
FlUMeng().init( preInit: false)
已经按这样调用了两次，目前还是获取不到安卓的数据，是不是还有什么步骤遗漏了呀？

**Comment by iOSyan** [comment]
已经获取到数据了，十分感谢

**Comment by disonwei** [comment]
> 

已经进行了预初始化 与 正式初始化 ，安卓依旧没有进行统计。 请问下你是怎么做的？

**Comment by Wayaer** [comment]
> 

现在免费版的 数据都是明天才显示，今天只记录昨天的数据

**Comment by Wayaer** [comment]
> > 
> 
> 已经进行了预期初始化与正式初始化，安卓依旧没有进行统计。请问下你是怎么做的？

目前友盟免费版数据都是隔天才显示，明天才能显示今天的数据

**Comment by iOSyan** [comment]
我是除了预初始化 与 正式初始化，然后对照友盟官方文档把安卓工程App 对应build.gradle配置脚本的dependencies都加上才有数据。[https://developer.umeng.com/docs/119267/detail/118584](url)

**Comment by disonwei** [comment]
> 我是除了预初始化 与 正式初始化，然后对照友盟官方文档把安卓工程App 对应build.gradle配置脚本的dependencies都加上才有数据。[https://developer.umeng.com/docs/119267/detail/118584](url)

今天又按照友盟文档 maven自动集成（推荐）方法添加了配置 。依旧统计不到。哎 
日志报
 E/UMConfigure(31965): 检测到未调用隐私授权API，详情见：https://developer.umeng.com/docs/119267/detail/182050
不知道和这个有没有关系。

**Comment by Wayaer** [comment]
> > 我是除了预初始化 与 正式初始化，然后对照友盟官方文档把安卓工程App 对应build.gradle配置脚本的dependencies都加上才有数据。[https://developer.umeng.com/docs/119267/detail/118584](url)
> 
> 今天又按照友盟文档 maven自动集成（推荐）方法添加了配置 。依旧统计不到。哎 日志报 E/UMConfigure(31965): 检测到未调用隐私授权API，详情见：https://developer.umeng.com/docs/119267/detail/182050 不知道和这个有没有关系。

预初始化和初始化中间延迟2秒试试看

**Comment by iOSyan** [comment]
> https://developer.umeng.com/docs/119267/detail/118584

文档上的这两个都添加了吗
![WX20230316-101713@2x](https://user-images.githubusercontent.com/12389901/225493674-603bfa3a-a63a-40cc-8b47-832f031558f6.png)


![WX20230316-102123@2x](https://user-images.githubusercontent.com/12389901/225493626-8c25acc0-bd31-4284-9532-e177f05ff4de.png)

**Comment by okerivy** [comment]
> > 
> 
> 预初始化 `FlUMeng().init( preInit: true)` 正式初始化 `FlUMeng().init( preInit: false)` 初始化方法需要调用两次一次预初始化 一次正式初始化， 预初始化一般放在同意授权之前，正式初始化放在授权之后

没有找到这个字段 preInit ? 去掉了吗？

**Comment by Wayaer** [comment]
> > > 
> > 
> > 
> > 预初始化 `FlUMeng().init( preInit: true)` 正式初始化 `FlUMeng().init( preInit: false)` 初始化方法需要调用两次一次预初始化 一次正式初始化， 预初始化一般放在同意授权之前，正式初始化放在授权之后
> 
> 没有找到这个字段 preInit ? 去掉了吗？

![image](https://github.com/Wayaer/fl_umeng/assets/17231965/7e3cc6ea-0b52-4689-9433-59974a7970d0)
