### ISSUE TITLE
Android 提示“基础组件库完整性自检未通过！请检查应用混淆配置。“

### ISSUE THREAD

**Issue by XuJiancheng** [Wayaer/fl_umeng#23]
D/UMLog   (23072): 统计SDK常见问题索引贴 详见链接 http://developer.umeng.com/docs/66650/cate/66650
I/UMLog   (23072): 统计SDK初始化成功
I/flutter (23072): Umeng 初始化成功 = true
W/m.xxx.test(23072): Accessing hidden method Landroid/os/Build;->getString(Ljava/lang/String;)Ljava/lang/String; (unsupported, reflection, allowed)
E/m.xxx.test(23072): Invalid ID 0x00000000.
W/System.err(23072): android.content.res.Resources$NotFoundException: String resource ID #0x0
W/System.err(23072): 	at android.content.res.Resources.getText(Resources.java:502)
W/System.err(23072): 	at android.content.res.Resources.getString(Resources.java:598)
W/System.err(23072): 	at com.umeng.umzid.ZIDManager.a(:18)
W/System.err(23072): 	at com.umeng.umzid.ZIDManager.a(:34)
W/System.err(23072): 	at com.umeng.umzid.ZIDManager$b.run(:1)
W/System.err(23072): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/System.err(23072): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(23072): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
W/System.err(23072): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(23072): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(23072): 	at java.lang.Thread.run(Thread.java:930)
I/UMLog   (23072): *com.umeng.commonsdk.a
I/UMLog   (23072): 基础组件库完整性自检未通过！请检查应用混淆配置。
I/UMLog   (23072): 统计SDK版本号: 9.5.6
I/UMLog   (23072): ZID SDK版本号: 1.6.3

**Comment by Wayaer** [comment]
```groovy
android {
    buildTypes {
        release {
            // 添加混淆配置
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'consumer-rules.pro'
        }
        debug {
            // 添加混淆配置
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'consumer-rules.pro'
        }
    }
}
```
