### ISSUE TITLE
检测到未调用隐私授权AP

### ISSUE THREAD

**Issue by tudosxxx** [Wayaer/fl_umeng#24]
检测到未调用隐私授权API，详情见：https://developer.umeng.com/docs/119267/detail/182050

安卓上 这个需不需要处理。

**Comment by Wayaer** [comment]
先调用预初始化 完成后再 正式初始化

**Comment by gujintao1900** [comment]
在同意隐私后调用 UMConfigure.submitPolicyGrantResult 这个设置授权结果就不会有这个提示，其他没任何影响。这个需要插件增加api，用来同步隐私结果

**Comment by Wayaer** [comment]
> 在同意隐私后调用 UMConfigure.submitPolicyGrantResult 这个设置授权结果就不会有这个提示，其他没任何影响。这个需要插件增加api，用来同步隐私结果

只有安卓需要添加吧？

**Comment by Wayaer** [comment]
已更新版本
