### ISSUE TITLE
无法通过集成测试看到实时数据

### ISSUE THREAD

**Issue by xupengpai** [Wayaer/fl_umeng#25]
如题，现在是在init之前调用preInit的，如果不在Application.onCreate里面调用preInit方法就无法通过官方的集成测试看到实时数据，至于实际的数据上报有没有问题就不知道了。
我反复测试过，只要在Application.onCreate里面调用了preInit，就没问题，跟了下preInit的代码，没找到原因。
只测试了android，不确定iOS有没有问题。

**Comment by Wayaer** [comment]
目前最新版，只调用一次初始化就可以了，在android原生层自动调用了预初始化和初始化两步操作。实时数据目前好像是要商务版才可以。
