### ISSUE TITLE
Android不能实时统计到数据，log有个获取资源的报错

### ISSUE THREAD

**Issue by zhouzongfu** [Wayaer/fl_umeng#3]
在看板不能实时更新启动次数等数据，iOS可以，看log,有报获取资源的错误，这个我应该如何修改？
W/.yueyou.jx3ton(20594): Accessing hidden method Landroid/os/Build;->getString(Ljava/lang/String;)Ljava/lang/String; (greylist, reflection, allowed)
E/.yueyou.jx3ton(20594): Invalid ID 0x00000000.
W/System.err(20594): android.content.res.Resources$NotFoundException: String resource ID #0x0
W/System.err(20594): 	at android.content.res.Resources.getText(Resources.java:459)
W/System.err(20594): 	at android.content.res.MiuiResources.getText(MiuiResources.java:97)
W/System.err(20594): 	at android.content.res.Resources.getString(Resources.java:552)
W/System.err(20594): 	at com.umeng.umzid.ZIDManager.a(:21)
W/System.err(20594): 	at com.umeng.umzid.ZIDManager.b(:5)
W/System.err(20594): 	at com.umeng.umzid.ZIDManager$b.run(Unknown Source:4)
W/System.err(20594): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/System.err(20594): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(20594): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
W/System.err(20594): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(20594): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(20594): 	at java.lang.Thread.run(Thread.java:923)
I/UMLog   (20594): 统计SDK版本号: 9.3.8
I/UMLog   (20594): ZID SDK版本号: 1.2.2
I/MobclickAgent(20594): module init:azio

**Comment by Wayaer** [comment]
这个打正式包 就没有，实时看板数据有延迟，

**Comment by sunjianan9900** [comment]
ios 有实时数据，但是安卓没有，1天了还没有测试时候的数据，后台显示未上报

**Comment by Wayaer** [comment]
看看是不是你的key设置错了，我这边几个项目 都没问题，都可以统计到数据

**Comment by Wayaer** [comment]
> ios有实时数据，但是安卓没有，1天了还没有测试时候的数据，后台显示未上报

看看是不是你的key设置错了，我这边几个项目 都没问题，都可以统计到数据

**Comment by sunjianan9900** [comment]
> > ios有实时数据，但是安卓没有，1天了还没有测试时候的数据，后台显示未上报
> 
> 看看是不是你的key设置错了，我这边几个项目 都没问题，都可以统计到数据

安卓你请求权限了吗？我安卓和ios都只是网络权限

**Comment by Wayaer** [comment]
> > > ios有实时数据，但是安卓没有，1天了还没有测试时候的数据，后台显示未上报
> > 
> > 
> > 看看是不是你的key设置错了，我这边几个项目 都没问题，都可以统计到数据
> 
> 安卓你请求权限了吗？我安卓和ios都只是网络权限

https://developer.umeng.com/docs/119267/detail/118584 看看官方的吧

**Comment by panzikeji** [comment]
我的android也是没有数据
