### ISSUE TITLE
bug(Android): 设置用户账号显示来源长度超过限制

### ISSUE THREAD

**Issue by pspdada** [Wayaer/fl_umeng#30]
代码：await FlUMeng().signIn(user.id, provider: 'Phone');
![image](https://github.com/Wayaer/fl_umeng/assets/51039403/fbe4abe2-5a52-4320-9109-03462f8a939f)
插件版本：  fl_umeng: ^3.6.1
[✓] Flutter (Channel stable, 3.19.1, on Microsoft Windows [版本 10.0.22631.3155], locale zh-CN)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.0 Preview 1.0)
[✓] Android Studio (version 2023.1)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by Wayaer** [comment]
你的userId太长了

**Comment by pspdada** [comment]
userId 是这样的格式：9529ebbb-b055-4138-97b3-0cbdc6ae1cc5
我把账号来源 provider 删掉之后就不会有这些错误提示

**Comment by Wayaer** [comment]
这个错误是友盟sdk报的错，得看看友盟的文档，不过按照日志 好像是 userid 和 provider 一起不能超过32个字符

**Comment by Wayaer** [comment]
你可以尝试把userId 裁短一点看看，加上 provider
