### ISSUE TITLE
小米审核不过

### ISSUE THREAD

**Issue by IceTears1** [Wayaer/fl_umeng#32]
![image](https://github.com/Wayaer/fl_umeng/assets/18476318/e8174640-7a52-4984-ab1a-b1dc0b14f131)
wen'xi问下这种的怎么解决

**Comment by IceTears1** [comment]
同意隐私协议之后才初始化的

**Comment by Wayaer** [comment]
你要在隐私政策里添加友盟sdk 使用规则，添加三方共享清单
![image](https://github.com/Wayaer/fl_umeng/assets/17231965/29433b76-bb2c-4e45-9d33-96bb017d42d3)

**Comment by IceTears1** [comment]
现在的问题是没有初始化之前 手机 android id

**Comment by IceTears1** [comment]
并且在隐私政策弹窗页 （还没有初始化友盟）如果点击了页面会触发友盟的  FPS 监听

**Comment by Wayaer** [comment]
> 现在的问题是没有初始化之前 手机 android id

没有初始化 ，目前是不会获取android Id的 我们自己app 都一直再用并审核上架的，

**Comment by IceTears1** [comment]
但是小米商店 机审给的结果是 Jpush 和Umeng 未初始化之前获取 android ID  SIM 卡等信息
请问你们上架小米商店了？
我纯  flutter项目

**Comment by Wayaer** [comment]
> 但是小米商店 机审给的结果是 Jpush 和Umeng 未初始化之前获取 android ID SIM 卡等信息 请问你们上架小米商店了？ 我纯 flutter项目

上架了,纯flutter 应用,都用到了友盟，极光推送 没用到

**Comment by IceTears1** [comment]
![image](https://github.com/Wayaer/fl_umeng/assets/18476318/34e7aa62-e8b2-41ed-ad9b-5b6041a9a83d)

**Comment by Wayaer** [comment]
> ![image](https://private-user-images.githubusercontent.com/18476318/347289443-34e7aa62-e8b2-41ed-ad9b-5b6041a9a83d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1OTQ2MDksIm5iZiI6MTcyMDU5NDMwOSwicGF0aCI6Ii8xODQ3NjMxOC8zNDcyODk0NDMtMzRlN2FhNjItZThiMi00MWVkLWFkOWItNWI2MDQxYTlhODNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA2NTE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5YmZjMDEwZDlmMGJmNzg2ZGQ3ZmFjZTYzYWE4NDFiOTQzOGU4YmE0NzFjODJlZWMyMmVlMTdhNWFiYzBmMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DnapXoNX7t6e6N2dquOxpbEH43wLJO8INVgHsaLRIUw)

你是通过ym包名判断是友盟的么？

**Comment by IceTears1** [comment]
![image](https://github.com/Wayaer/fl_umeng/assets/18476318/6b96ea88-1708-414d-8231-efc0ae01f3ed)

**Comment by IceTears1** [comment]
所有的初始化均在点击 同意隐私协议之后

**Comment by IceTears1** [comment]
umeng_apm_sdk: ^2.2.1
  umeng_common_sdk: ^1.2.7

**Comment by Wayaer** [comment]
> umeng_apm_sdk: ^2.2.1 umeng_common_sdk: ^1.2.7

你这不是我的包啊，你这个用的官方的包

**Comment by IceTears1** [comment]
咦

**Comment by IceTears1** [comment]
fl_umeng: ^3.6.1

**Comment by IceTears1** [comment]
用了这个

**Comment by Wayaer** [comment]
> 用了这个

看看你的pubspec  dependencies

**Comment by IceTears1** [comment]
统计分析用的 fl_umeng: ^3.6.1    apm用的官方的
莫非有冲突

**Comment by Wayaer** [comment]
> 统计分析用的 fl_umeng: ^3.6.1 apm用的官方的 莫非有冲突

你把 官方的apm删了试试看，官方的apm同样会依赖他们的统计，fl_umeng目前我用的 审核基本都过了不存在你说的问题

**Comment by Wayaer** [comment]
> 统计分析用的 fl_umeng: ^3.6.1 apm用的官方的 莫非有冲突

而且官方的flutter包很久没更新了，老版本一直都有问题,

**Comment by IceTears1** [comment]
OK
你的包apm 也OK的？

**Comment by Wayaer** [comment]
> OK 你的包apm 也OK的？

我那个apm 可以用，只是比较简陋，只能检测原生层面的异常，和一些自定义的异常上报

**Comment by IceTears1** [comment]
OK  我研究下
多谢
