### ISSUE TITLE
> Task :fl_umeng:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by pandawengogo** [Wayaer/fl_umeng#33]
打包apk的时候报了这个错误，确实解决不了，可以帮忙看看吗？

**Comment by pandawengogo** [comment]
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
    编译这里少了这个东西，可以帮忙加上吗？

**Comment by Wayaer** [comment]
https://github.com/Wayaer/fl_umeng/blob/58a56acf04147f1af27d877815fc9bb5278c6064/fl_umeng/example/android/app/build.gradle#L10
参考下example

**Comment by songyu1998628** [comment]
这个问题怎么解决的

**Comment by Wayaer** [comment]
> 这个问题怎么解决的

android/build.gradle

添加
`
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_21
    }
`
参考下example

**Comment by songyu1998628** [comment]
集成成功 初始化成功之后安卓没有新增用户是什么原因

**Comment by Wayaer** [comment]
> 集成成功 初始化成功之后安卓没有新增用户是什么原因

友盟非商务版不是实时的，隔天看看

**Comment by ZhuSky** [comment]
还要注意 settings.gradle 的配置，不然还是不行

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version '8.3.2' apply false
    id "org.jetbrains.kotlin.android" version "2.0.20" apply false
}
