### ISSUE TITLE
页面停留-怎么传数据呢？我看api不支持。

### ISSUE THREAD

**Issue by shaoting0730** [Wayaer/fl_umeng#34]
`

      FlUMeng().onPageStart('key');     
     
      FlUMeng() .onPageEnd('key');     

`

不能传值上去么？

`

      FlUMeng().onPageStart('key'，用户id);     
     
      FlUMeng()  .onPageEnd('key'，用户 id);    
 
`

**Comment by Wayaer** [comment]
https://developer.umeng.com/docs/119267/detail/118637#ca804e024dusp
原生Api 似乎是不支持传值的

**Comment by Wayaer** [comment]
https://github.com/Wayaer/fl_umeng/blob/58a56acf04147f1af27d877815fc9bb5278c6064/fl_umeng/lib/fl_umeng.dart#L94
看下example  有自定义事件

**Comment by shaoting0730** [comment]
@Wayaer   自定义事件可以，但是页面不可以。OK，谢谢~
