### ISSUE TITLE
2.0.0初始化报错空指针问题

### ISSUE THREAD

**Issue by xxm-sz** [Wayaer/fl_umeng#7]
按照你放在main函数内初始化，或空指针问题。放到其他地方正常。

**Comment by xxm-sz** [comment]
E/flutter (10980): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter (10980): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
E/flutter (10980): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
E/flutter (10980): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
E/flutter (10980): #3      FlUMeng.setLogEnabled (package:fl_umeng/fl_umeng.dart:97:24)
E/flutter (10980): #4      main (package:headset/main.dart:22:20)
E/flutter (10980): #5      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
E/flutter (10980): #6      _rootRun (dart:async/zone.dart:1354:13)
E/flutter (10980): #7      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (10980): #8      _runZoned (dart:async/zone.dart:1789:10)
E/flutter (10980): #9      runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter (10980): #10     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
E/flutter (10980): #11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter (10980): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (10980): 
E/flutter (10980): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter (10980): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
E/flutter (10980): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
E/flutter (10980): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
E/flutter (10980): #3      FlUMeng.setPageCollectionModeManual (package:fl_umeng/fl_umeng.dart:64:24)
E/flutter (10980): #4      main (package:headset/main.dart:23:20)
E/flutter (10980): #5      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
E/flutter (10980): #6      _rootRun (dart:async/zone.dart:1354:13)
E/flutter (10980): #7      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (10980): #8      _runZoned (dart:async/zone.dart:1789:10)
E/flutter (10980): #9      runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter (10980): #10     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
E/flutter (10980): #11     _delayEntrypointInvocation.<anonymous closure>

**Comment by Wayaer** [comment]
那我改下文档是不是就好了？
